steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 'deploy', 'get-lotto-numbers',
    '--runtime', 'python39',
    '--trigger-http',
    '--allow-unauthenticated',
    '--entry-point', 'get_lotto_numbers',
    '--region', 'us-central1', # <--- 여기를 변경된 리전으로 수정!
    '--source', '.',
    '--gen1'
  ]
timeout: 600s
logsBucket: 'gs://cloud-build-logs-hosunoh-lotto'